"""
Training loop for ObserverNeuralNetwork.

Synthetic time-series data is generated by default for demonstration.
Replace the DataLoader section with your own dataset for real use.
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from observer_nn import ModelConfig, ObserverNeuralNetwork, init_weights, count_parameters


def observer_diversity_loss(contexts: list) -> torch.Tensor:
    """Penalises low variance in observer context vectors to prevent collapse."""
    total = sum(-ctx.var(dim=0).mean() for ctx in contexts)
    return total / len(contexts)


def make_synthetic_data(config: ModelConfig, n_samples: int = 256):
    # seq_len chosen to contain exactly 2 beats
    seq_len = config.beat_samples * 2
    x = torch.randn(n_samples, seq_len, config.input_dim)
    y = torch.randint(0, config.output_dim, (n_samples,))
    return TensorDataset(x, y)


def build_optimizer(model: nn.Module, lr: float = 3e-4, weight_decay: float = 1e-2):
    no_decay = {"bias", "LayerNorm.weight", "LayerNorm.bias"}
    decay_params = [
        p for n, p in model.named_parameters()
        if p.requires_grad and not any(nd in n for nd in no_decay)
    ]
    nodecay_params = [
        p for n, p in model.named_parameters()
        if p.requires_grad and any(nd in n for nd in no_decay)
    ]
    return torch.optim.AdamW(
        [
            {"params": decay_params,   "weight_decay": weight_decay},
            {"params": nodecay_params, "weight_decay": 0.0},
        ],
        lr=lr,
    )


def train(
    config: ModelConfig | None = None,
    epochs: int = 5,
    batch_size: int = 8,
    lr: float = 3e-4,
    aux_weight: float = 0.01,
    device: str = "cpu",
):
    if config is None:
        config = ModelConfig()

    model = ObserverNeuralNetwork(config).to(device)
    model.apply(init_weights)
    print(f"Model parameters: {count_parameters(model):,}")

    dataset = make_synthetic_data(config)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    optimizer = build_optimizer(model, lr=lr)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=lr,
        steps_per_epoch=len(loader),
        epochs=epochs,
    )
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        correct = 0
        total = 0

        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            optimizer.zero_grad()
            logits, internals = model(batch_x)

            main_loss = criterion(logits, batch_y)
            # Flatten all context vectors across beats and harmonic cycles
            all_ctxs = [ctx for beat in internals["contexts"] for ctx in beat]
            aux_loss = observer_diversity_loss(all_ctxs) if all_ctxs else torch.tensor(0.0)
            loss = main_loss + aux_weight * aux_loss

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()

            total_loss += loss.item() * batch_x.size(0)
            preds = logits.argmax(dim=-1)
            correct += (preds == batch_y).sum().item()
            total += batch_x.size(0)

        avg_loss = total_loss / total
        acc = correct / total
        print(f"Epoch {epoch}/{epochs}  loss={avg_loss:.4f}  acc={acc:.3f}")

    return model


if __name__ == "__main__":
    # Small config for quick demonstration
    config = ModelConfig(
        input_dim=16,
        hidden_dim=64,
        n_qubits=4,
        n_qlayers=1,
        output_dim=5,
        n_harmonics=2,
        sample_rate=100,
    )
    train(config=config, epochs=3, batch_size=4)
